name: Build Executable

on:
  push:
    branches:
      - main

jobs:
  build:

    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: [3.9]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Build Executable
      run: |
        pyinstaller --onefile 1BoringEPub2PDF3GUI.py

    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: 1BoringEPub2PDF3GUI-${{ matrix.os }}
        path: dist/1BoringEPub2PDF3GUI*
